name: cure_team_2
description: A Flutter Clean Architecture project with BLoC (Cubit)

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.19.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  get_it: ^9.2.0
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.2
  flutter_svg: ^2.2.0
  flutter_spinkit: ^5.2.2
  country_code_picker: ^3.4.1
  pin_code_fields: ^8.0.1
  device_preview: ^1.3.1
  table_calendar: ^3.1.3
  intl: ^0.20.2
  dotted_border: ^2.1.0
  easy_date_timeline: ^2.0.9
  iconly: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500

    - family: Georgia
      fonts:
        - asset: assets/fonts/georgia.ttf
flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants
  filename: assets.dart
